### ISSUE TITLE
I am trying to upgrade from V2.2.01 to V3.0.0 but it errors out.

### ISSUE THREAD

**Issue by dynamicaccesssolutions** [vtortola/WebSocketListener#126]
I am using the vtortola.WebsocketListener library in a c# project built on .Net V 4.5.2. I recently tried to update my nuget package and it keeps erroring out with the folloing error message 

' Error		Could not install package 'vtortola.WebSocketListener 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	' , any help is greatly appreciated.

**Comment by vtortola** [comment]
I just merged a PR that adds support for 4.5. Please get latest version from repository and try.

**Comment by dynamicaccesssolutions** [comment]
Hi, an Update from V2.2.0.1 to V2.2.4.0 was successful but 2.2.4.0 -> 3.0.0.0 still fails with the same error message. I am trying to update it through Nuget in VS 2015 if that helps.

**Comment by vtortola** [comment]
Did you try with the Nuget or with the source in this repository?

**Comment by dynamicaccesssolutions** [comment]
I am trying to update it through **Nuget** in VS 2015 if that helps. I am doing all of the updating through Nuget in VS 2015. Update from V2.2.0.1 to V2.2.4.0 was using the **Nuget package manager** in VS 2015 as well.

**Comment by dynamicaccesssolutions** [comment]
I have yet to try it with the source in this repository
